architecture:
- 25
- 25
- 25
batch_size: 32
dataset: composite
dropout: 0.0
epochs: 501
experiment_name: '[25, 25, 25]_lr0.0001'
global_seed: 42
learning_rate: 0.0001
model_seed: 101
momentum: 0.9
output_dir: outputs/composite_data_anim
save_epochs:
- 0
- 1
- 2
- 3
- 4
- 6
- 8
- 10
save_interval: 1
