# Config.yaml file
#
#
experiment_name: "default_experiment"
architecture : [3,3,3] # Number and layout of hidden layers
optimizer:
  optimizer: "SGD"
  learning_rate: 0.1
training_params:
  epochs: 10000
  
