experiment_name: "moons_75"
dataset: "moons"
output_dir: "outputs/exp_1_capacity"

# Model Architecture
architecture: [75, 75, 75]  # Hidden layers
dropout: 0.0

# DETERMINISM SETTINGS
global_seed: 42    # Controls the Train/Test split and Shuffle order
model_seed: 101    # Controls ONLY the weight initialization

# Training Hyperparameters
epochs: 151
batch_size: 32
optimizer: "SGD"
learning_rate: 0.001
momentum: 0.9

# Data specific settings
noise: 0.1          # Geometric noise (for moons/circles) or label noise
test_size: 0.2


# SAVING STRATEGY
# 1. Save everyth epochs
save_interval: 10

# 2. AND save these specific epochs (dense at the start)
save_epochs: [0, 1, 2, 3, 4, 6, 8, 10]